"use client";

import type { ToolRuntime } from "./types";

const loaders: Record<string, () => Promise<ToolRuntime>> = {
  "add-commas-to-numbers": () => import("./transforms/add-commas-to-numbers").then((m) => { const t = m.addCommasToNumbersTool; return { slug: t.slug, options: t.options, transform: t.transform, requiresInput: t.requiresInput, inputCount: t.inputCount, outputMode: t.outputMode, supportsSwap: t.supportsSwap, inputPlaceholder: t.inputPlaceholder }; }),
  "add-line-breaks": () => import("./transforms/add-line-breaks").then((m) => { const t = m.addLineBreaksTool; return { slug: t.slug, options: t.options, transform: t.transform, requiresInput: t.requiresInput, inputCount: t.inputCount, outputMode: t.outputMode, supportsSwap: t.supportsSwap, inputPlaceholder: t.inputPlaceholder }; }),
  "add-line-numbers": () => import("./transforms/add-line-numbers").then((m) => { const t = m.addLineNumbersTool; return { slug: t.slug, options: t.options, transform: t.transform, requiresInput: t.requiresInput, inputCount: t.inputCount, outputMode: t.outputMode, supportsSwap: t.supportsSwap, inputPlaceholder: t.inputPlaceholder }; }),
  "add-prefix-suffix": () => import("./transforms/add-prefix-suffix").then((m) => { const t = m.addPrefixSuffixTool; return { slug: t.slug, options: t.options, transform: t.transform, requiresInput: t.requiresInput, inputCount: t.inputCount, outputMode: t.outputMode, supportsSwap: t.supportsSwap, inputPlaceholder: t.inputPlaceholder }; }),
  "bold-text-generator": () => import("./transforms/bold-text-generator").then((m) => { const t = m.boldTextGeneratorTool; return { slug: t.slug, options: t.options, transform: t.transform, requiresInput: t.requiresInput, inputCount: t.inputCount, outputMode: t.outputMode, supportsSwap: t.supportsSwap, inputPlaceholder: t.inputPlaceholder }; }),
  "center-text": () => import("./transforms/center-text").then((m) => { const t = m.centerTextTool; return { slug: t.slug, options: t.options, transform: t.transform, requiresInput: t.requiresInput, inputCount: t.inputCount, outputMode: t.outputMode, supportsSwap: t.supportsSwap, inputPlaceholder: t.inputPlaceholder }; }),
  "concatenate-text": () => import("./transforms/concatenate-text").then((m) => { const t = m.concatenateTextTool; return { slug: t.slug, options: t.options, transform: t.transform, requiresInput: t.requiresInput, inputCount: t.inputCount, outputMode: t.outputMode, supportsSwap: t.supportsSwap, inputPlaceholder: t.inputPlaceholder }; }),
  "convert-case": () => import("./transforms/convert-case").then((m) => { const t = m.convertCaseTool; return { slug: t.slug, options: t.options, transform: t.transform, requiresInput: t.requiresInput, inputCount: t.inputCount, outputMode: t.outputMode, supportsSwap: t.supportsSwap, inputPlaceholder: t.inputPlaceholder }; }),
  "cursive-text-generator": () => import("./transforms/cursive-text-generator").then((m) => { const t = m.cursiveTextGeneratorTool; return { slug: t.slug, options: t.options, transform: t.transform, requiresInput: t.requiresInput, inputCount: t.inputCount, outputMode: t.outputMode, supportsSwap: t.supportsSwap, inputPlaceholder: t.inputPlaceholder }; }),
  "difference-checker": () => import("./transforms/difference-checker").then((m) => { const t = m.differenceCheckerTool; return { slug: t.slug, options: t.options, transform: t.transform, requiresInput: t.requiresInput, inputCount: t.inputCount, outputMode: t.outputMode, supportsSwap: t.supportsSwap, inputPlaceholder: t.inputPlaceholder }; }),
  "email-extractor": () => import("./transforms/email-extractor").then((m) => { const t = m.emailExtractorTool; return { slug: t.slug, options: t.options, transform: t.transform, requiresInput: t.requiresInput, inputCount: t.inputCount, outputMode: t.outputMode, supportsSwap: t.supportsSwap, inputPlaceholder: t.inputPlaceholder }; }),
  "extract-column": () => import("./transforms/extract-column").then((m) => { const t = m.extractColumnTool; return { slug: t.slug, options: t.options, transform: t.transform, requiresInput: t.requiresInput, inputCount: t.inputCount, outputMode: t.outputMode, supportsSwap: t.supportsSwap, inputPlaceholder: t.inputPlaceholder }; }),
  "filler-text": () => import("./transforms/filler-text").then((m) => { const t = m.fillerTextTool; return { slug: t.slug, options: t.options, transform: t.transform, requiresInput: t.requiresInput, inputCount: t.inputCount, outputMode: t.outputMode, supportsSwap: t.supportsSwap, inputPlaceholder: t.inputPlaceholder }; }),
  "find-replace": () => import("./transforms/find-replace").then((m) => { const t = m.findReplaceTool; return { slug: t.slug, options: t.options, transform: t.transform, requiresInput: t.requiresInput, inputCount: t.inputCount, outputMode: t.outputMode, supportsSwap: t.supportsSwap, inputPlaceholder: t.inputPlaceholder }; }),
  "html-encode-decode": () => import("./transforms/html-encode-decode").then((m) => { const t = m.htmlEncodeDecodeTool; return { slug: t.slug, options: t.options, transform: t.transform, requiresInput: t.requiresInput, inputCount: t.inputCount, outputMode: t.outputMode, supportsSwap: t.supportsSwap, inputPlaceholder: t.inputPlaceholder }; }),
  "html-escape-unescape": () => import("./transforms/html-escape-unescape").then((m) => { const t = m.htmlEscapeUnescapeTool; return { slug: t.slug, options: t.options, transform: t.transform, requiresInput: t.requiresInput, inputCount: t.inputCount, outputMode: t.outputMode, supportsSwap: t.supportsSwap, inputPlaceholder: t.inputPlaceholder }; }),
  "italic-text-generator": () => import("./transforms/italic-text-generator").then((m) => { const t = m.italicTextGeneratorTool; return { slug: t.slug, options: t.options, transform: t.transform, requiresInput: t.requiresInput, inputCount: t.inputCount, outputMode: t.outputMode, supportsSwap: t.supportsSwap, inputPlaceholder: t.inputPlaceholder }; }),
  "justify-text": () => import("./transforms/justify-text").then((m) => { const t = m.justifyTextTool; return { slug: t.slug, options: t.options, transform: t.transform, requiresInput: t.requiresInput, inputCount: t.inputCount, outputMode: t.outputMode, supportsSwap: t.supportsSwap, inputPlaceholder: t.inputPlaceholder }; }),
  "normalize-unicode-text": () => import("./transforms/normalize-unicode-text").then((m) => { const t = m.normalizeUnicodeTextTool; return { slug: t.slug, options: t.options, transform: t.transform, requiresInput: t.requiresInput, inputCount: t.inputCount, outputMode: t.outputMode, supportsSwap: t.supportsSwap, inputPlaceholder: t.inputPlaceholder }; }),
  "old-english-text-generator": () => import("./transforms/old-english-text-generator").then((m) => { const t = m.oldEnglishTextGeneratorTool; return { slug: t.slug, options: t.options, transform: t.transform, requiresInput: t.requiresInput, inputCount: t.inputCount, outputMode: t.outputMode, supportsSwap: t.supportsSwap, inputPlaceholder: t.inputPlaceholder }; }),
  "pad-text": () => import("./transforms/pad-text").then((m) => { const t = m.padTextTool; return { slug: t.slug, options: t.options, transform: t.transform, requiresInput: t.requiresInput, inputCount: t.inputCount, outputMode: t.outputMode, supportsSwap: t.supportsSwap, inputPlaceholder: t.inputPlaceholder }; }),
  "pronounceable-password": () => import("./transforms/pronounceable-password").then((m) => { const t = m.pronounceablePasswordTool; return { slug: t.slug, options: t.options, transform: t.transform, requiresInput: t.requiresInput, inputCount: t.inputCount, outputMode: t.outputMode, supportsSwap: t.supportsSwap, inputPlaceholder: t.inputPlaceholder }; }),
  "random-email-generator": () => import("./transforms/random-email-generator").then((m) => { const t = m.randomEmailGeneratorTool; return { slug: t.slug, options: t.options, transform: t.transform, requiresInput: t.requiresInput, inputCount: t.inputCount, outputMode: t.outputMode, supportsSwap: t.supportsSwap, inputPlaceholder: t.inputPlaceholder }; }),
  "random-number-generator": () => import("./transforms/random-number-generator").then((m) => { const t = m.randomNumberGeneratorTool; return { slug: t.slug, options: t.options, transform: t.transform, requiresInput: t.requiresInput, inputCount: t.inputCount, outputMode: t.outputMode, supportsSwap: t.supportsSwap, inputPlaceholder: t.inputPlaceholder }; }),
  "random-string-generator": () => import("./transforms/random-string-generator").then((m) => { const t = m.randomStringGeneratorTool; return { slug: t.slug, options: t.options, transform: t.transform, requiresInput: t.requiresInput, inputCount: t.inputCount, outputMode: t.outputMode, supportsSwap: t.supportsSwap, inputPlaceholder: t.inputPlaceholder }; }),
  "random-word-generator": () => import("./transforms/random-word-generator").then((m) => { const t = m.randomWordGeneratorTool; return { slug: t.slug, options: t.options, transform: t.transform, requiresInput: t.requiresInput, inputCount: t.inputCount, outputMode: t.outputMode, supportsSwap: t.supportsSwap, inputPlaceholder: t.inputPlaceholder }; }),
  "remove-duplicate-lines": () => import("./transforms/remove-duplicate-lines").then((m) => { const t = m.removeDuplicateLinesTool; return { slug: t.slug, options: t.options, transform: t.transform, requiresInput: t.requiresInput, inputCount: t.inputCount, outputMode: t.outputMode, supportsSwap: t.supportsSwap, inputPlaceholder: t.inputPlaceholder }; }),
  "remove-empty-lines": () => import("./transforms/remove-empty-lines").then((m) => { const t = m.removeEmptyLinesTool; return { slug: t.slug, options: t.options, transform: t.transform, requiresInput: t.requiresInput, inputCount: t.inputCount, outputMode: t.outputMode, supportsSwap: t.supportsSwap, inputPlaceholder: t.inputPlaceholder }; }),
  "remove-emojis": () => import("./transforms/remove-emojis").then((m) => { const t = m.removeEmojisTool; return { slug: t.slug, options: t.options, transform: t.transform, requiresInput: t.requiresInput, inputCount: t.inputCount, outputMode: t.outputMode, supportsSwap: t.supportsSwap, inputPlaceholder: t.inputPlaceholder }; }),
  "remove-letter-accents": () => import("./transforms/remove-letter-accents").then((m) => { const t = m.removeLetterAccentsTool; return { slug: t.slug, options: t.options, transform: t.transform, requiresInput: t.requiresInput, inputCount: t.inputCount, outputMode: t.outputMode, supportsSwap: t.supportsSwap, inputPlaceholder: t.inputPlaceholder }; }),
  "remove-line-breaks": () => import("./transforms/remove-line-breaks").then((m) => { const t = m.removeLineBreaksTool; return { slug: t.slug, options: t.options, transform: t.transform, requiresInput: t.requiresInput, inputCount: t.inputCount, outputMode: t.outputMode, supportsSwap: t.supportsSwap, inputPlaceholder: t.inputPlaceholder }; }),
  "remove-lines-containing": () => import("./transforms/remove-lines-containing").then((m) => { const t = m.removeLinesContainingTool; return { slug: t.slug, options: t.options, transform: t.transform, requiresInput: t.requiresInput, inputCount: t.inputCount, outputMode: t.outputMode, supportsSwap: t.supportsSwap, inputPlaceholder: t.inputPlaceholder }; }),
  "remove-unwanted-characters": () => import("./transforms/remove-unwanted-characters").then((m) => { const t = m.removeUnwantedCharactersTool; return { slug: t.slug, options: t.options, transform: t.transform, requiresInput: t.requiresInput, inputCount: t.inputCount, outputMode: t.outputMode, supportsSwap: t.supportsSwap, inputPlaceholder: t.inputPlaceholder }; }),
  "replace-smart-straight-quotes": () => import("./transforms/replace-smart-straight-quotes").then((m) => { const t = m.replaceSmartStraightQuotesTool; return { slug: t.slug, options: t.options, transform: t.transform, requiresInput: t.requiresInput, inputCount: t.inputCount, outputMode: t.outputMode, supportsSwap: t.supportsSwap, inputPlaceholder: t.inputPlaceholder }; }),
  "reverse-letters": () => import("./transforms/reverse-letters").then((m) => { const t = m.reverseLettersTool; return { slug: t.slug, options: t.options, transform: t.transform, requiresInput: t.requiresInput, inputCount: t.inputCount, outputMode: t.outputMode, supportsSwap: t.supportsSwap, inputPlaceholder: t.inputPlaceholder }; }),
  "reverse-list": () => import("./transforms/reverse-list").then((m) => { const t = m.reverseListTool; return { slug: t.slug, options: t.options, transform: t.transform, requiresInput: t.requiresInput, inputCount: t.inputCount, outputMode: t.outputMode, supportsSwap: t.supportsSwap, inputPlaceholder: t.inputPlaceholder }; }),
  "reverse-words": () => import("./transforms/reverse-words").then((m) => { const t = m.reverseWordsTool; return { slug: t.slug, options: t.options, transform: t.transform, requiresInput: t.requiresInput, inputCount: t.inputCount, outputMode: t.outputMode, supportsSwap: t.supportsSwap, inputPlaceholder: t.inputPlaceholder }; }),
  "sort-text": () => import("./transforms/sort-text").then((m) => { const t = m.sortTextTool; return { slug: t.slug, options: t.options, transform: t.transform, requiresInput: t.requiresInput, inputCount: t.inputCount, outputMode: t.outputMode, supportsSwap: t.supportsSwap, inputPlaceholder: t.inputPlaceholder }; }),
  "spaces-to-tabs": () => import("./transforms/spaces-to-tabs").then((m) => { const t = m.spacesToTabsTool; return { slug: t.slug, options: t.options, transform: t.transform, requiresInput: t.requiresInput, inputCount: t.inputCount, outputMode: t.outputMode, supportsSwap: t.supportsSwap, inputPlaceholder: t.inputPlaceholder }; }),
  "split-text": () => import("./transforms/split-text").then((m) => { const t = m.splitTextTool; return { slug: t.slug, options: t.options, transform: t.transform, requiresInput: t.requiresInput, inputCount: t.inputCount, outputMode: t.outputMode, supportsSwap: t.supportsSwap, inputPlaceholder: t.inputPlaceholder }; }),
  "strip-html-tags": () => import("./transforms/strip-html-tags").then((m) => { const t = m.stripHtmlTagsTool; return { slug: t.slug, options: t.options, transform: t.transform, requiresInput: t.requiresInput, inputCount: t.inputCount, outputMode: t.outputMode, supportsSwap: t.supportsSwap, inputPlaceholder: t.inputPlaceholder }; }),
  "strong-password-generator": () => import("./transforms/strong-password-generator").then((m) => { const t = m.strongPasswordGeneratorTool; return { slug: t.slug, options: t.options, transform: t.transform, requiresInput: t.requiresInput, inputCount: t.inputCount, outputMode: t.outputMode, supportsSwap: t.supportsSwap, inputPlaceholder: t.inputPlaceholder }; }),
  "swap-columns": () => import("./transforms/swap-columns").then((m) => { const t = m.swapColumnsTool; return { slug: t.slug, options: t.options, transform: t.transform, requiresInput: t.requiresInput, inputCount: t.inputCount, outputMode: t.outputMode, supportsSwap: t.supportsSwap, inputPlaceholder: t.inputPlaceholder }; }),
  "tabs-to-spaces": () => import("./transforms/tabs-to-spaces").then((m) => { const t = m.tabsToSpacesTool; return { slug: t.slug, options: t.options, transform: t.transform, requiresInput: t.requiresInput, inputCount: t.inputCount, outputMode: t.outputMode, supportsSwap: t.supportsSwap, inputPlaceholder: t.inputPlaceholder }; }),
  "url-encode-decode": () => import("./transforms/url-encode-decode").then((m) => { const t = m.urlEncodeDecodeTool; return { slug: t.slug, options: t.options, transform: t.transform, requiresInput: t.requiresInput, inputCount: t.inputCount, outputMode: t.outputMode, supportsSwap: t.supportsSwap, inputPlaceholder: t.inputPlaceholder }; }),
  "url-extractor": () => import("./transforms/url-extractor").then((m) => { const t = m.urlExtractorTool; return { slug: t.slug, options: t.options, transform: t.transform, requiresInput: t.requiresInput, inputCount: t.inputCount, outputMode: t.outputMode, supportsSwap: t.supportsSwap, inputPlaceholder: t.inputPlaceholder }; }),
  "username-generator": () => import("./transforms/username-generator").then((m) => { const t = m.usernameGeneratorTool; return { slug: t.slug, options: t.options, transform: t.transform, requiresInput: t.requiresInput, inputCount: t.inputCount, outputMode: t.outputMode, supportsSwap: t.supportsSwap, inputPlaceholder: t.inputPlaceholder }; }),
  "word-count": () => import("./transforms/word-count").then((m) => { const t = m.wordCountTool; return { slug: t.slug, options: t.options, transform: t.transform, requiresInput: t.requiresInput, inputCount: t.inputCount, outputMode: t.outputMode, supportsSwap: t.supportsSwap, inputPlaceholder: t.inputPlaceholder }; }),
  "word-wrap": () => import("./transforms/word-wrap").then((m) => { const t = m.wordWrapTool; return { slug: t.slug, options: t.options, transform: t.transform, requiresInput: t.requiresInput, inputCount: t.inputCount, outputMode: t.outputMode, supportsSwap: t.supportsSwap, inputPlaceholder: t.inputPlaceholder }; }),
};

export const loadToolRuntime = async (slug: string): Promise<ToolRuntime | null> => {
  const loader = loaders[slug];
  if (!loader) return null;
  return loader();
};
